USE [master]
GO
--NOTE: This is using SQL Server 2014
--NOTE: You will have to modify filenames to match your SQL Server instance name. e.g: C:\Program Files\Microsoft SQL Server\MSSQL12.<YOURINSTANCEHERE>\MSSQL\DATA\WOW.mdf

/****** Object:  Database [WOW]    Script Date: 10/22/2014 11:35:14 PM ******/
CREATE DATABASE [WOW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WOW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SCOTTSQL\MSSQL\DATA\WOW.mdf' , SIZE = 281280KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [ICONFILEGROUP] CONTAINS FILESTREAM  DEFAULT
( NAME = N'fsWOW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SCOTTSQL\MSSQL\DATA\fsWOW.mdf' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'WOW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SCOTTSQL\MSSQL\DATA\WOW_log.ldf' , SIZE = 20096KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WOW] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WOW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WOW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WOW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WOW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WOW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WOW] SET ARITHABORT OFF 
GO

ALTER DATABASE [WOW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WOW] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [WOW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WOW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WOW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WOW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WOW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WOW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WOW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WOW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WOW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WOW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WOW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WOW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WOW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WOW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WOW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WOW] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WOW] SET  MULTI_USER 
GO

ALTER DATABASE [WOW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WOW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WOW] SET FILESTREAM( NON_TRANSACTED_ACCESS = READ_ONLY ) 
GO

ALTER DATABASE [WOW] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WOW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WOW] SET  READ_WRITE 
GO

